/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'customSolutions' : IDL.Null,
  'processOptimization' : IDL.Null,
  'aiSupportAgents' : IDL.Null,
  'automationBots' : IDL.Null,
});
export const CompanyProfile = IDL.Record({
  'dateOfBirth' : IDL.Int,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'updatedAt' : IDL.Int,
  'companyWebsite' : IDL.Text,
  'companyAddress' : IDL.Text,
  'lastName' : IDL.Text,
  'servicesNeeded' : IDL.Vec(ServiceType),
  'firstName' : IDL.Text,
});
export const UserId = IDL.Principal;
export const TeamMember = IDL.Record({
  'name' : IDL.Text,
  'designation' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateTeamMember' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateCompanyProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ServiceType),
      ],
      [],
      [],
    ),
  'deleteCompanyProfile' : IDL.Func([], [], []),
  'deleteTeamMember' : IDL.Func([IDL.Text], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompanyProfile' : IDL.Func([], [CompanyProfile], ['query']),
  'getCompanyProfileById' : IDL.Func([UserId], [CompanyProfile], ['query']),
  'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getTeamMembersById' : IDL.Func([UserId], [IDL.Vec(TeamMember)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'customSolutions' : IDL.Null,
    'processOptimization' : IDL.Null,
    'aiSupportAgents' : IDL.Null,
    'automationBots' : IDL.Null,
  });
  const CompanyProfile = IDL.Record({
    'dateOfBirth' : IDL.Int,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'updatedAt' : IDL.Int,
    'companyWebsite' : IDL.Text,
    'companyAddress' : IDL.Text,
    'lastName' : IDL.Text,
    'servicesNeeded' : IDL.Vec(ServiceType),
    'firstName' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const TeamMember = IDL.Record({
    'name' : IDL.Text,
    'designation' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateTeamMember' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateCompanyProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ServiceType),
        ],
        [],
        [],
      ),
    'deleteCompanyProfile' : IDL.Func([], [], []),
    'deleteTeamMember' : IDL.Func([IDL.Text], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompanyProfile' : IDL.Func([], [CompanyProfile], ['query']),
    'getCompanyProfileById' : IDL.Func([UserId], [CompanyProfile], ['query']),
    'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getTeamMembersById' : IDL.Func([UserId], [IDL.Vec(TeamMember)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };