/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CompanyProfile {
  'dateOfBirth' : bigint,
  'createdAt' : bigint,
  'email' : string,
  'updatedAt' : bigint,
  'companyWebsite' : string,
  'companyAddress' : string,
  'lastName' : string,
  'servicesNeeded' : Array<ServiceType>,
  'firstName' : string,
}
export type ServiceType = { 'customSolutions' : null } |
  { 'processOptimization' : null } |
  { 'aiSupportAgents' : null } |
  { 'automationBots' : null };
export interface TeamMember { 'name' : string, 'designation' : string }
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateTeamMember' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateCompanyProfile' : ActorMethod<
    [string, string, string, bigint, string, string, Array<ServiceType>],
    undefined
  >,
  'deleteCompanyProfile' : ActorMethod<[], undefined>,
  'deleteTeamMember' : ActorMethod<[string], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompanyProfile' : ActorMethod<[], CompanyProfile>,
  'getCompanyProfileById' : ActorMethod<[UserId], CompanyProfile>,
  'getTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getTeamMembersById' : ActorMethod<[UserId], Array<TeamMember>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];