/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export interface TeamMember {
    name: string;
    designation: string;
}
export interface CompanyProfile {
    dateOfBirth: bigint;
    createdAt: bigint;
    email: string;
    updatedAt: bigint;
    companyWebsite: string;
    companyAddress: string;
    lastName: string;
    servicesNeeded: Array<ServiceType>;
    firstName: string;
}
export enum ServiceType {
    customSolutions = "customSolutions",
    processOptimization = "processOptimization",
    aiSupportAgents = "aiSupportAgents",
    automationBots = "automationBots"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addOrUpdateTeamMember(name: string, designation: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createOrUpdateCompanyProfile(email: string, firstName: string, lastName: string, dateOfBirth: bigint, companyWebsite: string, companyAddress: string, servicesNeeded: Array<ServiceType>): Promise<void>;
    deleteCompanyProfile(): Promise<void>;
    deleteTeamMember(name: string): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getCompanyProfile(): Promise<CompanyProfile>;
    getCompanyProfileById(userId: UserId): Promise<CompanyProfile>;
    getTeamMembers(): Promise<Array<TeamMember>>;
    getTeamMembersById(userId: UserId): Promise<Array<TeamMember>>;
    isCallerAdmin(): Promise<boolean>;
}
import type { CompanyProfile as _CompanyProfile, ServiceType as _ServiceType, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addOrUpdateTeamMember(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateTeamMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateTeamMember(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createOrUpdateCompanyProfile(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: Array<ServiceType>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateCompanyProfile(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_vec_n3(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateCompanyProfile(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_vec_n3(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async deleteCompanyProfile(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCompanyProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCompanyProfile();
            return result;
        }
    }
    async deleteTeamMember(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeamMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeamMember(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompanyProfile(): Promise<CompanyProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanyProfile();
                return from_candid_CompanyProfile_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanyProfile();
            return from_candid_CompanyProfile_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompanyProfileById(arg0: UserId): Promise<CompanyProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanyProfileById(arg0);
                return from_candid_CompanyProfile_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanyProfileById(arg0);
            return from_candid_CompanyProfile_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamMembers(): Promise<Array<TeamMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamMembers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamMembers();
            return result;
        }
    }
    async getTeamMembersById(arg0: UserId): Promise<Array<TeamMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamMembersById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamMembersById(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
}
function from_candid_CompanyProfile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompanyProfile): CompanyProfile {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateOfBirth: bigint;
    createdAt: bigint;
    email: string;
    updatedAt: bigint;
    companyWebsite: string;
    companyAddress: string;
    lastName: string;
    servicesNeeded: Array<_ServiceType>;
    firstName: string;
}): {
    dateOfBirth: bigint;
    createdAt: bigint;
    email: string;
    updatedAt: bigint;
    companyWebsite: string;
    companyAddress: string;
    lastName: string;
    servicesNeeded: Array<ServiceType>;
    firstName: string;
} {
    return {
        dateOfBirth: value.dateOfBirth,
        createdAt: value.createdAt,
        email: value.email,
        updatedAt: value.updatedAt,
        companyWebsite: value.companyWebsite,
        companyAddress: value.companyAddress,
        lastName: value.lastName,
        servicesNeeded: from_candid_vec_n10(_uploadFile, _downloadFile, value.servicesNeeded),
        firstName: value.firstName
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customSolutions: null;
} | {
    processOptimization: null;
} | {
    aiSupportAgents: null;
} | {
    automationBots: null;
}): ServiceType {
    return "customSolutions" in value ? ServiceType.customSolutions : "processOptimization" in value ? ServiceType.processOptimization : "aiSupportAgents" in value ? ServiceType.aiSupportAgents : "automationBots" in value ? ServiceType.automationBots : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ServiceType>): Array<ServiceType> {
    return value.map((x)=>from_candid_ServiceType_n11(_uploadFile, _downloadFile, x));
}
function to_candid_ServiceType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    customSolutions: null;
} | {
    processOptimization: null;
} | {
    aiSupportAgents: null;
} | {
    automationBots: null;
} {
    return value == ServiceType.customSolutions ? {
        customSolutions: null
    } : value == ServiceType.processOptimization ? {
        processOptimization: null
    } : value == ServiceType.aiSupportAgents ? {
        aiSupportAgents: null
    } : value == ServiceType.automationBots ? {
        automationBots: null
    } : value;
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ServiceType>): Array<_ServiceType> {
    return value.map((x)=>to_candid_ServiceType_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
